apiVersion: v1
kind: Service
metadata:
  name: java-internship-order-service
  labels:
    app: java-internship-order-service
spec:
  selector:
    app: java-internship-order-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
  