spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

USER_SERVICE_URL: ${USER_SERVICE_URL:http://user-service:8081}

server:
  port: ${SERVER_PORT:8083}
