
spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      auto-startup: false
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_TEST_SECRET}
          enabled: false
  datasource:
    url: ${DB_URL:jdbc:tc:postgresql:16-alpine:///order_service_test}
    username: ${DB_USERNAME:test}
    password: ${DB_PASSWORD:test}
    driver-class-name: ${DB_DRIVER:org.testcontainers.jdbc.ContainerDatabaseDriver}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: test
    drop-first: true


USER_SERVICE_URL: ${USER_SERVICE_URL}


spring.cloud.openfeign.client.config.default.connectTimeout: 1000
spring.cloud.openfeign.client.config.default.readTimeout: 1000


resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 500ms
        wait-duration-in-open-state: 1s
        sliding-window-size: 3
        permitted-number-of-calls-in-half-open-state: 1
    instances:
      userService:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 1s
        cancel-running-future: true


logging:
  level:
    com.javainternshiporderservice: INFO
    org.springframework.security: WARN
    com.github.tomakehurst.wiremock: WARN
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


server:
  port: 0


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

app:
  kafka:
    enabled: false
