spring:
  application:
    name: JavaInternship
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

# User Service configuration
USER_SERVICE_URL: ${USER_SERVICE_URL:http://localhost:8080}

# Resilience4j Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 2s
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
    instances:
      userService:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 4s
        cancel-running-future: true

